// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebNewsFinal.Models;

namespace WebNewsFinal.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220115152130_BaslangicMigrate")]
    partial class BaslangicMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebNewsFinal.Models.Haber", b =>
                {
                    b.Property<long>("HaberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("KategoriId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kapak_foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kisa_icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("yayin_tarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("HaberId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Haberler");
                });

            modelBuilder.Entity("WebNewsFinal.Models.Kategori", b =>
                {
                    b.Property<long>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("baslik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("WebNewsFinal.Models.Kullanici", b =>
                {
                    b.Property<long>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("admin_mi")
                        .HasColumnType("bit");

                    b.Property<string>("avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("WebNewsFinal.Models.Haber", b =>
                {
                    b.HasOne("WebNewsFinal.Models.Kategori", "Kategori")
                        .WithMany("Haberler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNewsFinal.Models.Kullanici", "Kullanici")
                        .WithMany("Haberler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("WebNewsFinal.Models.Kategori", b =>
                {
                    b.Navigation("Haberler");
                });

            modelBuilder.Entity("WebNewsFinal.Models.Kullanici", b =>
                {
                    b.Navigation("Haberler");
                });
#pragma warning restore 612, 618
        }
    }
}
